## #############################################################################
# The linter section handles global settings
## #############################################################################
[linter]
# Globally disable one or more rules by name, e.g. with `disable_rules = ["ID_DIFFERENT_FROM_JDEX"]`
disable_rules = []
# Output machine-readable JSON instead of human-readable terminal output
json_output = false
# File patterns to ignore anywhere they appear; these support rudimentary globbing
ignore = [".stignore", ".stfolder", ".git*"]

## #############################################################################
# The system section handles defining your system format
## #############################################################################
[system]

## #############################################################################
# The system.jdex section defines how your JDex is stored on the disk
## #############################################################################
[system.jdex]
# The path to begin JDex structure at.
path = "~/Documents/00-09 System-management area/00 System-management category ⚙️/00.00 JDex for the Life Admin System 📇"
# File patterns to ignore just in the JDex
ignore = [".obsidian"]
template = "standard_jdex"

## #############################################################################
#  system.default defines the *default* structure used by any roots to check
## #############################################################################
[system.default]
template = "standard_system"

## #############################################################################
# system.roots define folders that should be organized according to your JD
# system; for example, you might have ~/Documents as one root and ~/Dropbox
# as another.
## #############################################################################
[[system.roots]]
# The name to refer to the root as in errors/JSON output
name = "Documents"
# The path to the files
path = "~/Documents"
# Any ignore patterns that apply only to that set of files
ignore = [".trash"]

# [[system.roots]]
# name = "Dropbox"
# path = "~/Dropbox"
# ignore = []

# You can override the default structure for just *one* location if you want,
# e.g. if you only wanted work packages and nothing else in your dropbox
# [[system.roots.children]]
# name = "Work Packages Area"
# format = "W0000-W9999 /*Area/"
# id = "W0000-W9999"
# # This allows us to not need a JDex entry for something
# no_jdex_entry = true

# [[system.roots.children.children]]
# name = "Work Package"
# format = "W/####WPID/~/##AC/./##ID/ /*WPName/"
# # You can override an expected JDex entry with `entry`
# entry = "Something wildly arbitrary for /=WPID/; you should change this"
# id = "W/=WPID/"
# allow_arbitrary_contents = true
#
[template]
imports = ["./standard_templates.toml"]
