## #############################################################################
# The linter section handles global settings
## #############################################################################
[linter]
# Globally disable one or more rules by name, e.g. with `disable_rules = ["ID_DIFFERENT_FROM_JDEX"]`
disable_rules = []
# Output machine-readable JSON instead of human-readable terminal output
json_output = false
# File patterns to ignore anywhere they appear; these support rudimentary globbing
ignore = [".stignore", ".stfolder", ".git*"]

## #############################################################################
# The system section handles defining your system format
## #############################################################################
[system]
## #############################################################################
# The system.jdex section defines how your JDex is stored on the disk
## #############################################################################
[system.jdex]
# The path to begin JDex structure within.
path = "~/Knowledge"
# File patterns to ignore just in the JDex
ignore = [".obsidian", ".trash"]

# `children` specifies folders on the disk that are expected in the JDex.  These
# may then define `notes`, which specify files on the disk (generally they are
# going to be Markdown notes, but they don't have to be) that make up the JDex.
[[system.jdex.children]]
# The name to refer to the note type as in errors/JSON output
name = "JDex Branch Folder"
# The expected format of the note
format = "B/##BB/ /*Branch/"

[[system.jdex.children.children]]
name = "JDex Branch Index Folder"
format = "C/=BB/.00 📇 Index"

[[system.jdex.children.children.notes]]
name = "JDex Branch Note"
format = "B/=BB/ /=Branch/.md"

# `ids` specifies what IDs a note creates, and what their full "name" is.  Note
# that a note *can* allow more than one, e.g. 10.00 allows Area 10-19, Category
# 10, and ID 10.00 to exist. Note that you can use bound segments in this.
[[system.jdex.children.children.notes.ids]]
id = "B/=BB/"
entry = "B/=BB/ /=Branch/"

[[system.jdex.children.children.notes]]
name = "JDex Branch Index Note"
format = "C/=BB/./##ID/ /*Name/.md"

[[system.jdex.children.children.notes.ids]]
id = "C/=BB/./=ID/"
entry = "C/=BB/./=ID/ /=Name/"

[[system.jdex.children.children.notes]]
name = "Nest To Cache Note"
format = "N/=BB/./####ID/~C/=BB/./##RelID/ /*Nest/.md"

[[system.jdex.children.children.notes.ids]]
id = "N/=BB/./=ID/"
entry = "N/=BB/./=ID/~C/=BB/./=RelID/ /=Nest/"

[[system.jdex.children.children.notes]]
name = "Nest To Nest Note"
format = "N/=BB/./####ID/~N/=BB/./####RelID/ /*Nest/.md"

[[system.jdex.children.children.notes.ids]]
id = "N/=BB/./=ID/"
entry = "N/=BB/./=ID/~N/=BB/./=RelID/ /=Nest/"

[[system.jdex.children.children.children]]
name = "Attachments Folder"
format = "Attachments"
allow_arbitrary_contents = true

[[system.jdex.children.children]]
name = "JDex Cache Non-Index Folder"
format = "C/=BB/./##ID/ /*Cache/"
allow_arbitrary_contents = true

[[system.jdex.children.children]]
name = "JDex Nest Non-Index Folder"
format = "N/=BB/./####ID/~/*Nest/"
allow_arbitrary_contents = true

[[system.roots]]
name = "Knowledge"
path = "~/Knowledge"
ignore = [".git", ".gitignore", ".obsidian", ".trash"]

[[system.roots.children]]
name = "Trunk"
format = "B/#T/0 /*Trunk/ ⬇️"
id = "B/=T/0"

[[system.roots.children.children]]
name = "Trunk Index"
format = "C/=T/0.00 📇 Index"
id = "C/=T/0.00"
allow_arbitrary_contents = true

[[system.roots.children]]
name = "Branch"
format = "B/##BB/ /*Branch/"
id = "B/=BB/"

[[system.roots.children.children]]
name = "Index"
format = "C/=BB/.00 📇 Index"
id = "C/=BB/.00"
allow_arbitrary_contents = true

[[system.roots.children.children]]
name = "Header"
format = "C/=BB/./#H/0 /*Header/ ⬇️"
id = "C/=BB/./=H/0"

# Disallow headers that don't match this format
[[system.roots.children.children]]
name = "Invalid Header Or Index"
format = "C/=BB/./#H/0 /*Header/"
id = "C/=BB/./=H/0"
forbidden = true

[[system.roots.children.children]]
name = "Inbox"
format = "C/=BB/.01 📥️ Inbox"
id = "C/=BB/.01"

# Disallow inboxes that don't match this format
[[system.roots.children.children]]
name = "Invalid Inbox"
format = "C/=BB/.01 /*Inbox/"
id = "C/=BB/.01"
forbidden = true

[[system.roots.children.children]]
name = "Cache"
format = "C/=BB/./##ID/ /*Cache/"

allow_arbitrary_contents = true
id = "C/=BB/./=ID/"

[[system.roots.children.children]]
name = "Nest"
format = "N/=BB/./####ID/~/*Nest/"
id = "N/=BB/./=ID/"
allow_arbitrary_contents = true

[[system.roots]]
name = "Caches"
path = "~/Caches"

[[system.roots]]
name = "Knowledge"
path = "~/Knowledge"
ignore = [".obsidian", ".trash"]

[[system.roots]]
name = "Nests"
path = "~/Nests"

[[system.roots.children]]
name = "Nest"
format = "N/##BB/./####ID/~/*Nest/"
id = "N/=BB/./=ID/"
allow_arbitrary_contents = true

[[system.default.children]]
name = "Trunk"
format = "B/#T/0 /*Trunk/ ⬇️"
id = "B/=T/0"

[[system.default.children]]
name = "Branch"
format = "B/##BB/ /*Branch/"
id = "B/=BB/"

## #############################################################################
# Here, we're defining standard zeros so that they are all named consistently
## #############################################################################
[[system.default.children.children]]
name = "Index"
format = "C/=BB/.00 📇 Index"
id = "C/=BB/.00"
allow_arbitrary_contents = true

[[system.default.children.children]]
name = "Invalid Index"
format = "C/=BB/.00/*Index/"
id = "C/=BB/.00"
forbidden = true

[[system.default.children.children]]
name = "Inbox"
format = "C/=BB/.01 📥️ Inbox"
id = "C/=BB/.01"

[[system.default.children.children]]
name = "Invalid Inbox"
format = "C/=BB/.01/*Inbox/"
id = "C/=BB/.01"
forbidden = true

[[system.default.children.children]]
name = "Control"
format = "C/=BB/.02 ✅ Control"
id = "C/=BB/.02"
allow_arbitrary_contents = true

[[system.default.children.children]]
name = "Invalid Control"
format = "C/=BB/.02/*Control/"
id = "C/=BB/.02"
forbidden = true

[[system.default.children.children]]
name = "Templates"
format = "C/=BB/.03 📑 Templates & Standards"
id = "C/=BB/.03"
allow_arbitrary_contents = true

[[system.default.children.children]]
name = "Invalid Templates"
format = "C/=BB/.03/*Templates/"
id = "C/=BB/.03"
forbidden = true

[[system.default.children.children]]
name = "Links"
format = "C/=BB/.04 🔗 Sources, Resources, & Links"
id = "C/=BB/.04"
allow_arbitrary_contents = true

[[system.default.children.children]]
name = "Invalid Links"
format = "C/=BB/.04/*Links/"
id = "C/=BB/.04"
forbidden = true

[[system.default.children.children]]
name = "Ideas"
format = "C/=BB/.05 💭 Inspiration, Ideas, & Percolation"
id = "C/=BB/.05"
allow_arbitrary_contents = true

[[system.default.children.children]]
name = "Invalid Ideas"
format = "C/=BB/.05/*Ideas/"
id = "C/=BB/.05"
forbidden = true

[[system.default.children.children]]
name = "Tags"
format = "C/=BB/.06 🏷️ Topics & Tags"
id = "C/=BB/.06"
allow_arbitrary_contents = true

[[system.default.children.children]]
name = "Invalid Tags"
format = "C/=BB/.06/*Tags/"
id = "C/=BB/.06"
forbidden = true

[[system.default.children.children]]
name = "Unused .07"
format = "C/=BB/.07/*Name/"
id = "C/=BB/.07"
forbidden = true

[[system.default.children.children]]
name = "Unused .08"
format = "C/=BB/.08/*Name/"
id = "C/=BB/.08"
forbidden = true

[[system.default.children.children]]
name = "ADR"
format = "C/=BB/.09 ⚖️ Decision Log"
id = "C/=BB/.09"
allow_arbitrary_contents = true

[[system.default.children.children]]
name = "Invalid ADR"
format = "C/=BB/.09/*ADR/"
id = "C/=BB/.09"
forbidden = true

## #############################################################################
# Ensure headers are empty and properly named
## #############################################################################
[[system.default.children.children]]
name = "Header"
format = "C/=BB/./#H/0 /*Header/ ⬇️"
id = "C/=BB/./=H/0"

# Disallow headers that don't match this format
[[system.default.children.children]]
name = "Invalid Header Or Index"
format = "C/=BB/./#H/0 /*Header/"
id = "C/=BB/./=H/0"
forbidden = true

## #############################################################################
# Actual Content
## #############################################################################
[[system.default.children.children]]
name = "Cache"
format = "C/=BB/./##ID/ /*Cache/"
allow_arbitrary_contents = true
id = "C/=BB/./=ID/"

[[system.default.children.children]]
name = "Nest"
format = "N/=BB/./####ID/~/*Nest/"
id = "N/=BB/./=ID/"
allow_arbitrary_contents = true
