## #############################################################################
# The linter section handles global settings
## #############################################################################
[linter]
# Globally disable one or more rules by name, e.g. with `disable_rules = ["ID_DIFFERENT_FROM_JDEX"]`
disable_rules = []
# Output machine-readable JSON instead of human-readable terminal output
json_output = false
# Ignore any JD configuration files present
ignore_environment = true
# File patterns to ignore anywhere they appear; these support rudimentary globbing
ignore = [".stignore", ".stfolder"]

## #############################################################################
# The system section handles defining your system format
## #############################################################################
[system]

## #############################################################################
# The system.jdex section defines how your JDex is stored on the disk
## #############################################################################
[system.jdex]
# The path to begin JDex structure within.
path = "~/Knowledge"
# File patterns to ignore just in the JDex
ignore = [".obsidian", ".trash", ".git*"]
# This will be appended to all *note* formats within the JDex; it is provided for convenience to allow format re-use between folders and files
note_extension = ".md"

# `children` specifies folders on the disk that are expected in the JDex.  These
# may then define `notes`, which specify files on the disk (generally they are
# going to be Markdown notes, but they don't have to be) that make up the JDex.
[[system.jdex.children]]
template = "trunk"
children = [{ template = "trunk_index", children = [{ template = "attachments_folder" }] }]

[[system.jdex.children]]
template = "branch"
children = [
  { template = "index", children = [{ template = "attachments_folder" }] },
  { template = "cache" },
  { template = "nest_to_nest" },
  { template = "nest_to_cache" },
]

[[system.roots]]
name = "Knowledge"
path = "~/Knowledge"
ignore = [".obsidian", ".trash", ".git*"]

[[system.roots.children]]
template = "trunk"
children = [{ template = "trunk_index", allow_arbitrary_contents = true }]

[[system.roots.children]]
template = "branch"
children = [
  { template = "index", allow_arbitrary_contents = true },
  { template = "bad_index" },
  { template = "inbox" },
  { template = "bad_inbox" },
  { template = "control" },
  { template = "bad_control" },
  { template = "templates" },
  { template = "bad_templates" },
  { template = "links" },
  { template = "bad_links" },
  { template = "ideas" },
  { template = "bad_ideas" },
  { template = "tags" },
  { template = "bad_tags" },
  { template = "unused_07" },
  { template = "unused_08" },
  { template = "adr" },
  { template = "bad_adr" },
  { template = "header" },
  { template = "bad_header" },
  { template = "cache" },
  { template = "nest_to_cache" },
  { template = "nest_to_nest" },
]

[[system.roots]]
name = "Caches"
path = "~/Caches"

[[system.roots.children]]
template = "trunk"

[[system.roots.children]]
template = "branch"
children = [
  { template = "bad_index" },
  { template = "inbox" },
  { template = "bad_inbox" },
  { template = "bad_control" },
  { template = "bad_links" },
  { template = "bad_tags" },
  { template = "bad_adr" },
  { template = "header" },
  { template = "cache" },
]

[[system.roots]]
name = "Nests"
path = "~/Nests"
children = [
  { template = "nest_to_cache_flat" },
  { template = "nest_to_nest_flat" },
]

[[system.roots]]
name = "Dropbox"
path = "~/Dropbox"
ignore = [".maestral*"]  # Ignore the folders Maestral uses
# Dropbox does not use anything but terminal folders;
children = [
  { template = "cache_flat" },
  { template = "nest_to_cache_flat" },
  { template = "nest_to_nest_flat" },
]

## #############################################################################
# Templates
## #############################################################################
[template.trunk]
name = "Trunk"
format = "B/#T/0 /*Trunk/ ⬇️"
id = "B/=T/0"
parent = "B/=T/0-/=T/9"

[[template.trunk.ids]]
id = "B/=T/0-/=T/9"
entry = "B/=T/0-/=T/9 /=Trunk/ ⬇️"

[template.branch]
name = "Branch"
format = "B/#T//#B/ /*Branch/"
id = "B/=T//=B/"
parent = "B/=T/0-/=T/9"

[template.cache]
name = "Cache"
format = "C/=T//=B/./##ID/ /*Cache/"
allow_arbitrary_contents = true
id = "C/=T//=B/./=ID/"
parent = "B/=T//=B/"

[template.cache_flat]
template = "cache"
format = "C/#T//#B/./##ID/ /*Cache/"

## #############################################################################
# Nests (Work Packages)
## #############################################################################
[template.nest_to_cache]
name = "Nest To Cache"
format = "N/=T//=B/./####ID/~C/=T//=B/./##RelID/ /*Nest/"
id = "N/=T//=B/./=ID/"
parent = "C/=T//=B/./=RelID/"
allow_arbitrary_contents = true

[template.nest_to_nest]
name = "Nest To Nest"
format = "N/=T//=B/./####ID/~N/=T//=B/./####RelID/ /*Nest/"
id = "N/=T//=B/./=ID/"
parent = "N/=T//=B/./=RelID/"
allow_arbitrary_contents = true

[template.nest_to_cache_flat]
template = "nest_to_cache"
format = "N/#T//#B/./####ID/~C/=T//=B/./##RelID/ /*Nest/"

[template.nest_to_nest_flat]
template = "nest_to_nest"
format = "N/#T//#B/./####ID/~N/=T//=B/./####RelID/ /*Nest/"

## #############################################################################
# The Standard Zeros
## #############################################################################
[template.zero]
format = "C/=T//=B/.0/#Z/ /*ZName/"
name = "Standard Zero"
id = "C/=T//=B/.0/=Z/"
parent = "B/=T//=B/"
allow_arbitrary_contents = true

[template.bad_zero]
name = "Invalid Standard Zero (Or Where It Doesn't Belong)"
format = "C/=T//=B/.0/#Z/ /*Name/"
id = "C/=T//=B/.0/=Z/"
forbidden = true

[template.index]
template = "zero"
bind = { Z = "0", ZName = "📇 Index" }
notes = [
  { template = "branch" },
  { template = "index" },
  { template = "bad_index" },
  { template = "inbox" },
  { template = "bad_inbox" },
  { template = "control" },
  { template = "bad_control" },
  { template = "templates" },
  { template = "bad_templates" },
  { template = "links" },
  { template = "bad_links" },
  { template = "ideas" },
  { template = "bad_ideas" },
  { template = "tags" },
  { template = "bad_tags" },
  { template = "unused_07" },
  { template = "unused_08" },
  { template = "adr" },
  { template = "bad_adr" },
  { template = "header" },
  { template = "bad_header" },
  { template = "cache" },
  { template = "nest_to_cache" },
  { template = "nest_to_nest" },
  { template = "cache" },
  { template = "nest_to_cache" },
  { template = "nest_to_nest" },
]
allow_arbitrary_contents = false

[template.trunk_index]
template = "index"
bind = { B = "0" }
notes = [{ template = "trunk" }, { template = "trunk_index" }]

[template.bad_index]
name = "Index Invalid Or Where It Doesn't Belong"
format = "C/=T//=B/.00/*Index/"
id = "C/=T//=B/.00"
forbidden = true

[template.inbox]
template = "zero"
bind = { Z = "1", ZName = "📥️ Inbox" }
allow_arbitrary_contents = false

[template.bad_inbox]
template = "bad_zero"
bind = { Z = "1" }

[template.control]
template = "zero"
bind = { Z = "2", ZName = "✅ Control" }

[template.bad_control]
template = "bad_zero"
bind = { Z = "2" }

[template.templates]
template = "zero"
bind = { Z = "3", ZName = "📑 Templates & Standards" }

[template.bad_templates]
template = "bad_zero"
bind = { Z = "3" }

[template.links]
template = "zero"
bind = { Z = "4", ZName = "🔗 Sources, Resources, & Links" }

[template.bad_links]
template = "bad_zero"
bind = { Z = "4" }

[template.ideas]
template = "zero"
bind = { Z = "5", ZName = "💭 Inspiration, Ideas, & Percolation" }

[template.bad_ideas]
template = "bad_zero"
bind = { Z = "5" }

[template.tags]
template = "zero"
bind = { Z = "6", ZName = "🏷️ Topics & Tags" }

[template.bad_tags]
template = "bad_zero"
bind = { Z = "6" }

[template.unused_07]
template = "bad_zero"
bind = { Z = "7" }

[template.unused_08]
template = "bad_zero"
bind = { Z = "8" }

[template.adr]
template = "zero"
bind = { Z = "9", ZName = "⚖️ Decision Log" }

[template.bad_adr]
template = "bad_zero"
bind = { Z = "9" }

[template.header]
name = "Header"
format = "C/=T//=B/./#H/0 /*Header/ ⬇️"
id = "C/=T//=B/./=H/0"
parent = "B/=T//=B/"

[template.bad_header]
name = "Invalid Header Or Index"
format = "C/=T//=B/./#H/0 /*Header/"
id = "C/=T//=B/./=H/0"
forbidden = true

[template.attachments_folder]
name = "Attachments Folder"
format = "Attachments"
allow_arbitrary_contents = true
