## #############################################################################
# The linter section handles global settings
## #############################################################################
[linter]
# Globally disable one or more rules by name, e.g. with `disable_rules = ["ID_DIFFERENT_FROM_JDEX"]`
disable_rules = []
# Output machine-readable JSON instead of human-readable terminal output
json_output = false
# Ignore any JD configuration files present
ignore_environment = true
# File patterns to ignore anywhere they appear; these support rudimentary globbing
ignore = [".stignore", ".stfolder", ".git*"]

## #############################################################################
# The system section handles defining your system format
## #############################################################################
[system]

## #############################################################################
# The system.jdex section defines how your JDex is stored on the disk
## #############################################################################
[system.jdex]
# The path to begin JDex structure within.
path = "~/Knowledge"
# File patterns to ignore just in the JDex
ignore = [".obsidian", ".trash"]

# `children` specifies folders on the disk that are expected in the JDex.  These
# may then define `notes`, which specify files on the disk (generally they are
# going to be Markdown notes, but they don't have to be) that make up the JDex.
[[system.jdex.children]]
template = "trunk"
children = [{ template = "trunk_index", children = [{ template = "attachments_folder" }] }]

[[system.jdex.children]]
template = "branch"
children = [
  { template = "index", children = [{ template = "attachments_folder" }] },
  { template = "cache" },
  { template = "nest_to_nest" },
  { template = "nest_to_cache" },
]

[[system.roots]]
name = "Knowledge"
path = "~/Knowledge"
ignore = [".git", ".gitignore", ".obsidian", ".trash"]

[[system.roots.children]]
template = "trunk"
children = [{ template = "trunk_index", allow_arbitrary_contents = true }]

[[system.roots.children]]
template = "branch"
children = [
  { template = "index", allow_arbitrary_contents = true },
  { template = "bad_index" },
  { template = "inbox" },
  { template = "bad_inbox" },
  { template = "control" },
  { template = "bad_control" },
  { template = "templates" },
  { template = "bad_templates" },
  { template = "links" },
  { template = "bad_links" },
  { template = "ideas" },
  { template = "bad_ideas" },
  { template = "tags" },
  { template = "bad_tags" },
  { template = "unused_07" },
  { template = "unused_08" },
  { template = "adr" },
  { template = "bad_adr" },
  { template = "header" },
  { template = "bad_header" },
  { template = "cache" },
  { template = "nest_to_cache" },
  { template = "nest_to_nest" },
]

[[system.roots]]
name = "Caches"
path = "~/Caches"

[[system.roots.children]]
template = "trunk"
children = []  # Outside of Knowledge, Trunks are just headers

[[system.roots.children]]
template = "branch"
children = [
  { template = "bad_index" },
  { template = "inbox" },
  { template = "bad_inbox" },
  { template = "bad_control" },
  { template = "bad_links" },
  { template = "bad_tags" },
  { template = "bad_adr" },
  { template = "header" },
  { template = "cache" },
]

[[system.roots]]
name = "Nests"
path = "~/Nests"
children = [
  { template = "nest_to_cache_flat" },
  { template = "nest_to_nest_flat" },
]

[[system.roots]]
name = "Dropbox"
path = "~/Dropbox"
ignore = [".maestral*"]  # Ignore the folders Maestral uses
# Dropbox does not use anything but terminal folders;
children = [
  # Notice how you can inline a non-template folder in with templates
  { name = "Cache", format = "C/#T//#B/./##ID/ /*Cache/", allow_arbitrary_contents = true, id = "C/=T//=B/./=ID/" },
  { template = "nest_to_cache_flat" },
  { template = "nest_to_nest_flat" },
]

## #############################################################################
# Templates
## #############################################################################
[template.trunk]
name = "Trunk"
format = "B/#T/0 /*Trunk/ ⬇️"
id = "B/=T/0"

[template.branch]
name = "Branch"
format = "B/#T//#B/ /*Branch/"
id = "B/=T//=B/"

[template.cache]
name = "Cache"
format = "C/=T//=B/./##ID/ /*Cache/"
allow_arbitrary_contents = true
id = "C/=T//=B/./=ID/"

## #############################################################################
# Nests (Work Packages)
## #############################################################################
[template.nest_to_cache]
name = "Nest To Cache"
format = "N/=T//=B/./####ID/~C/=T//=B/./##RelID/ /*Nest/"
id = "N/=T//=B/./=ID/"
allow_arbitrary_contents = true

[template.nest_to_nest]
name = "Nest To Nest"
format = "N/=T//=B/./####ID/~N/=T//=B/./####RelID/ /*Nest/"
id = "N/=T//=B/./=ID/"
allow_arbitrary_contents = true

[template.nest_to_nest_flat]
name = "Nest To Nest"
format = "N/#T//#B/./####ID/~N/=T//=B/./####RelID/ /*Nest/"
id = "N/=T//=B/./=ID/"
allow_arbitrary_contents = true

[template.nest_to_cache_flat]
name = "Nest To Cache"
format = "N/#T//#B/./####ID/~C/=T//=B/./##RelID/ /*Nest/"
id = "N/=T//=B/./=ID/"
allow_arbitrary_contents = true

## #############################################################################
# The Standard Zeros
## #############################################################################
[template.header]
name = "Header"
format = "C/=T//=B/./#H/0 /*Header/ ⬇️"
id = "C/=T//=B/./=H/0"

[template.bad_header]
name = "Invalid Header Or Index"
format = "C/=T//=B/./#H/0 /*Header/"
id = "C/=T//=B/./=H/0"
forbidden = true

[template.trunk_index]
name = "Index"
format = "C/=T/0.00 📇 Index"
id = "C/=T/0.00"
notes = [{ template = "trunk_note" }, { template = "trunk_index_note" }]

[template.index]
name = "Index"
format = "C/=T//=B/.00 📇 Index"
id = "C/=T//=B/.00"
notes = [{ template = "branch_note" }, { template = "cache_note" }, { template = "nest_to_cache_note" }, { template = "nest_to_nest_note" }]

[template.bad_index]
name = "Index Invalid Or Where It Doesn't Belong"
format = "C/=T//=B/.00/*Index/"
id = "C/=T//=B/.00"
forbidden = true

[template.inbox]
name = "Inbox"
format = "C/=T//=B/.01 📥️ Inbox"
id = "C/=T//=B/.01"

[template.bad_inbox]
name = "Invalid Inbox"
format = "C/=T//=B/.01/*Inbox/"
id = "C/=T//=B/.01"
forbidden = true

[template.control]
name = "Control"
format = "C/=T//=B/.02 ✅ Control"
id = "C/=T//=B/.02"
allow_arbitrary_contents = true

[template.bad_control]
name = "Control Invalid Or Where It Doesn't Belong"
format = "C/=T//=B/.02/*Control/"
id = "C/=T//=B/.02"
forbidden = true

[template.templates]
name = "Templates"
format = "C/=T//=B/.03 📑 Templates & Standards"
id = "C/=T//=B/.03"
allow_arbitrary_contents = true

[template.bad_templates]
name = "Invalid Templates"
format = "C/=T//=B/.03/*Templates/"
id = "C/=T//=B/.03"
forbidden = true

[template.links]
name = "Links"
format = "C/=T//=B/.04 🔗 Sources, Resources, & Links"
id = "C/=T//=B/.04"
allow_arbitrary_contents = true

[template.bad_links]
name = "Links Invalid Or Where It Doesn't Belong"
format = "C/=T//=B/.04/*Links/"
id = "C/=T//=B/.04"
forbidden = true

[template.ideas]
name = "Ideas"
format = "C/=T//=B/.05 💭 Inspiration, Ideas, & Percolation"
id = "C/=T//=B/.05"
allow_arbitrary_contents = true

[template.bad_ideas]
name = "Invalid Ideas"
format = "C/=T//=B/.05/*Ideas/"
id = "C/=T//=B/.05"
forbidden = true

[template.tags]
name = "Tags"
format = "C/=T//=B/.06 🏷️ Topics & Tags"
id = "C/=T//=B/.06"
allow_arbitrary_contents = true

[template.bad_tags]
name = "Tags Invalid Or Where It Doesn't Belong"
format = "C/=T//=B/.06/*Tags/"
id = "C/=T//=B/.06"
forbidden = true

[template.unused_07]
name = "Unused .07"
format = "C/=T//=B/.07/*Name/"
id = "C/=T//=B/.07"
forbidden = true

[template.unused_08]
name = "Unused .08"
format = "C/=T//=B/.08/*Name/"
id = "C/=T//=B/.08"
forbidden = true

[template.adr]
name = "ADR"
format = "C/=T//=B/.09 ⚖️ Decision Log"
id = "C/=T//=B/.09"
allow_arbitrary_contents = true

[template.bad_adr]
name = "ADR Invalid Or Where It Doesn't Belong"
format = "C/=T//=B/.09/*ADR/"
id = "C/=T//=B/.09"
forbidden = true

[template.attachments_folder]
name = "Attachments Folder"
format = "Attachments"
allow_arbitrary_contents = true

## #############################################################################
# Notes
## #############################################################################
[template.trunk_note]
name = "JDex Trunk Note"
format = "B/=T/0 /=Trunk/ ⬇️.md"

[[template.trunk_note.ids]]
id = "B/=T/0-/=T/9"
entry = "B/=T/0-/=T/9 /=Trunk/ ⬇️"

[[template.trunk_note.ids]]
id = "B/=T/0"
parent = "B/=T/0-/=T/9"
entry = "B/=T/0 /=Trunk/ ⬇️"

[template.trunk_index_note]
name = "JDex Trunk Index Note"
format = "C/=T/0.00 📇 Index.md"

[[template.trunk_index_note.ids]]
id = "C/=T/0.00"
parent = "B/=T/0"
entry = "C/=T/0.00 📇 Index"

[template.branch_note]
name = "JDex Branch Note"
format = "B/=T//=B/ /=Branch/.md"

[[template.branch_note.ids]]
id = "B/=T//=B/"
parent = "B/=T/0-/=T/9"
entry = "B/=T//=B/ /=Branch/"

[template.cache_note]
name = "JDex Cache Note"
format = "C/=T//=B/./##ID/ /*Name/.md"

[[template.cache_note.ids]]
id = "C/=T//=B/./=ID/"
parent = "B/=T//=B/"
entry = "C/=T//=B/./=ID/ /=Name/"

[template.nest_to_cache_note]
name = "Nest To Cache Note"
format = "N/=T//=B/./####ID/~C/=T//=B/./##RelID/ /*Nest/.md"

[[template.nest_to_cache_note.ids]]
id = "N/=T//=B/./=ID/"
parent = "C/=T//=B/./=RelID/"
entry = "N/=T//=B/./=ID/~C/=T//=B/./=RelID/ /=Nest/"

[template.nest_to_nest_note]
name = "Nest To Nest Note"
format = "N/=T//=B/./####ID/~N/=T//=B/./####RelID/ /*Nest/.md"

[[template.nest_to_nest_note.ids]]
id = "N/=T//=B/./=ID/"
parent = "N/=T//=B/./=RelID/"
entry = "N/=T//=B/./=ID/~N/=T//=B/./=RelID/ /=Nest/"
